system lavaBurn
{
	scale_velocity                              0.1
    scale                                       0.1 0.1 0.1
    technique 
    {
        visual_particle_quota                   80
        material                                mp_explosion_flame_02
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Box 
        {
            emission_rate                       40
            angle                               5
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             300
                max                             500
            }
            duration                            0.8
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             60
            }
            box_height                          1
        }
        affector                                Colour 
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.3  1 0.45098 0.235294 1
            time_colour                         0.5  1 0.45098 0.235294 1
            time_colour                         1    0 0 0 1
        }
        affector                                Scale 
        {
            xyz_scale                           200
        }
        affector                                TextureRotator 
        {
            use_own_rotation                    true
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -0.5
                max                             0.5
            }
        }
    }
}
