system bullet_spark
{
    scale_velocity                              0.05
    scale                                       0.05 0.05 0.05
    technique 
    {
        visual_particle_quota                   8
        material                                mp_hit_metal_sparkle
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    bottom_center
            billboard_rotation_type             vertex
        }
        emitter                                 Point 
        {
            emission_rate                       1800
            angle                               30
            time_to_live                        dyn_random
            {
                min                             0.1
                max                             0.8
            }
            velocity                            dyn_random
            {
                min                             400
                max                             900
            }
            duration                            0.3
            particle_width                      dyn_random
            {
                min                             5
                max                             10
            }
            particle_height                     dyn_random
            {
                min                             5
                max                             30
            }
            direction                           1 0.5 0
        }
        affector                                Colour 
        {
            time_colour                         0    0.941176 0.321569 0.137255 1
            time_colour                         0.7  0.941176 0.321569 0.137255 1
            time_colour                         1    0 0 0 0
        }
        affector                                LinearForce 
        {
            force_vector                        0 -2000 0
        }
        affector                                Scale 
        {
            xyz_scale                           -20
        }
        observer                                OnClear 
        {
            handler                             DoStopSystem 
            {
            }
        }
    }
}
